// Duplicate / delete for the admin listing list. Both re-assert permission
// server-side and run as the signed-in user, so RLS applies as well.
import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { assertCanEditListing } from "./admin.server";

const IdInput = z.object({ id: z.string().uuid() });

// Row fields the copy must not inherit: identity, publication state, counters
// and audit columns. The slug is regenerated by the database trigger.
const DROPPED = [
  "id",
  "slug",
  "status",
  "created_at",
  "updated_at",
  "published_at",
  "created_by",
  "updated_by",
  "view_count",
  "inquiry_count",
  "sold_price",
  "sold_at",
] as const;

/** Copy a listing as a fresh draft (without images) and return the new id. */
export const duplicateListing = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: unknown) => IdInput.parse(input))
  .handler(async ({ data, context }): Promise<{ id: string }> => {
    const { supabase, userId } = context;
    const { assertPermission } = await import("@/lib/auth/require-permission.server");
    await assertCanEditListing(supabase, userId, data.id);
    await assertPermission(supabase, userId, "listing.create");

    const { data: row, error } = await supabase
      .from("listings")
      .select("*")
      .eq("id", data.id)
      .maybeSingle();
    if (error) throw new Error(error.message);
    if (!row) throw new Error("Not found");

    const copy: Record<string, unknown> = { ...(row as Record<string, unknown>) };
    for (const key of DROPPED) delete copy[key];
    copy.status = "draft";

    const { data: created, error: insertError } = await supabase
      .from("listings")
      .insert(copy as never)
      .select("id")
      .maybeSingle();
    if (insertError || !created) {
      throw new Error(insertError?.message ?? "Duplicate failed");
    }
    return created as { id: string };
  });

/** Permanent delete; the database cascades images and inquiry references. */
export const deleteListing = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: unknown) => IdInput.parse(input))
  .handler(async ({ data, context }) => {
    const { supabase, userId } = context;
    const { assertPermission } = await import("@/lib/auth/require-permission.server");
    await assertCanEditListing(supabase, userId, data.id);
    await assertPermission(supabase, userId, "listing.delete");

    const { error } = await supabase.from("listings").delete().eq("id", data.id);
    if (error) throw new Error(error.message);
    return { ok: true as const };
  });
