/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleVerkauftRouteImport } from './routes/$locale.verkauft'
import { Route as LocaleVerkaufenRouteImport } from './routes/$locale.verkaufen'
import { Route as LocaleUeberMichRouteImport } from './routes/$locale.ueber-mich'
import { Route as LocaleKontaktRouteImport } from './routes/$locale.kontakt'
import { Route as LocaleImmobilienbewertungRouteImport } from './routes/$locale.immobilienbewertung'
import { Route as LocaleAuthRouteImport } from './routes/$locale.auth'
import { Route as LocaleAdminRouteImport } from './routes/$locale.admin'
import { Route as LocaleImmobilienIndexRouteImport } from './routes/$locale.immobilien.index'
import { Route as LocaleAdminIndexRouteImport } from './routes/$locale.admin.index'
import { Route as LocaleImmobilienSlugRouteImport } from './routes/$locale.immobilien.$slug'
import { Route as LocaleAuthResetPasswordRouteImport } from './routes/$locale.auth.reset-password'
import { Route as LocaleAuthLoginRouteImport } from './routes/$locale.auth.login'
import { Route as LocaleAuthForgotPasswordRouteImport } from './routes/$locale.auth.forgot-password'
import { Route as LocaleAdminTeamRouteImport } from './routes/$locale.admin.team'
import { Route as LocaleAdminSettingsRouteImport } from './routes/$locale.admin.settings'
import { Route as LocaleAdminListingsRouteImport } from './routes/$locale.admin.listings'
import { Route as LocaleAdminInquiriesRouteImport } from './routes/$locale.admin.inquiries'
import { Route as LocaleAdminContentRouteImport } from './routes/$locale.admin.content'
import { Route as LocaleAdminAnalyticsRouteImport } from './routes/$locale.admin.analytics'
import { Route as LocaleAdminSettingsIndexRouteImport } from './routes/$locale.admin.settings.index'
import { Route as LocaleAdminListingsIndexRouteImport } from './routes/$locale.admin.listings.index'
import { Route as LocaleAdminInquiriesIndexRouteImport } from './routes/$locale.admin.inquiries.index'
import { Route as LocaleAdminSettingsTabRouteImport } from './routes/$locale.admin.settings.$tab'
import { Route as LocaleAdminListingsNewRouteImport } from './routes/$locale.admin.listings.new'
import { Route as LocaleAdminListingsIdRouteImport } from './routes/$locale.admin.listings.$id'
import { Route as LocaleAdminInquiriesIdRouteImport } from './routes/$locale.admin.inquiries.$id'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleVerkauftRoute = LocaleVerkauftRouteImport.update({
  id: '/verkauft',
  path: '/verkauft',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleVerkaufenRoute = LocaleVerkaufenRouteImport.update({
  id: '/verkaufen',
  path: '/verkaufen',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleUeberMichRoute = LocaleUeberMichRouteImport.update({
  id: '/ueber-mich',
  path: '/ueber-mich',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleKontaktRoute = LocaleKontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleImmobilienbewertungRoute =
  LocaleImmobilienbewertungRouteImport.update({
    id: '/immobilienbewertung',
    path: '/immobilienbewertung',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleAuthRoute = LocaleAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminRoute = LocaleAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleImmobilienIndexRoute = LocaleImmobilienIndexRouteImport.update({
  id: '/immobilien/',
  path: '/immobilien/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminIndexRoute = LocaleAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleImmobilienSlugRoute = LocaleImmobilienSlugRouteImport.update({
  id: '/immobilien/$slug',
  path: '/immobilien/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAuthResetPasswordRoute = LocaleAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LocaleAuthRoute,
} as any)
const LocaleAuthLoginRoute = LocaleAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleAuthRoute,
} as any)
const LocaleAuthForgotPasswordRoute =
  LocaleAuthForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => LocaleAuthRoute,
  } as any)
const LocaleAdminTeamRoute = LocaleAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminSettingsRoute = LocaleAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminListingsRoute = LocaleAdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminInquiriesRoute = LocaleAdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminContentRoute = LocaleAdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminAnalyticsRoute = LocaleAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleAdminSettingsIndexRoute =
  LocaleAdminSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleAdminSettingsRoute,
  } as any)
const LocaleAdminListingsIndexRoute =
  LocaleAdminListingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleAdminListingsRoute,
  } as any)
const LocaleAdminInquiriesIndexRoute =
  LocaleAdminInquiriesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleAdminInquiriesRoute,
  } as any)
const LocaleAdminSettingsTabRoute = LocaleAdminSettingsTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => LocaleAdminSettingsRoute,
} as any)
const LocaleAdminListingsNewRoute = LocaleAdminListingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LocaleAdminListingsRoute,
} as any)
const LocaleAdminListingsIdRoute = LocaleAdminListingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LocaleAdminListingsRoute,
} as any)
const LocaleAdminInquiriesIdRoute = LocaleAdminInquiriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LocaleAdminInquiriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/admin': typeof LocaleAdminRouteWithChildren
  '/$locale/auth': typeof LocaleAuthRouteWithChildren
  '/$locale/immobilienbewertung': typeof LocaleImmobilienbewertungRoute
  '/$locale/kontakt': typeof LocaleKontaktRoute
  '/$locale/ueber-mich': typeof LocaleUeberMichRoute
  '/$locale/verkaufen': typeof LocaleVerkaufenRoute
  '/$locale/verkauft': typeof LocaleVerkauftRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/analytics': typeof LocaleAdminAnalyticsRoute
  '/$locale/admin/content': typeof LocaleAdminContentRoute
  '/$locale/admin/inquiries': typeof LocaleAdminInquiriesRouteWithChildren
  '/$locale/admin/listings': typeof LocaleAdminListingsRouteWithChildren
  '/$locale/admin/settings': typeof LocaleAdminSettingsRouteWithChildren
  '/$locale/admin/team': typeof LocaleAdminTeamRoute
  '/$locale/auth/forgot-password': typeof LocaleAuthForgotPasswordRoute
  '/$locale/auth/login': typeof LocaleAuthLoginRoute
  '/$locale/auth/reset-password': typeof LocaleAuthResetPasswordRoute
  '/$locale/immobilien/$slug': typeof LocaleImmobilienSlugRoute
  '/$locale/admin/': typeof LocaleAdminIndexRoute
  '/$locale/immobilien/': typeof LocaleImmobilienIndexRoute
  '/$locale/admin/inquiries/$id': typeof LocaleAdminInquiriesIdRoute
  '/$locale/admin/listings/$id': typeof LocaleAdminListingsIdRoute
  '/$locale/admin/listings/new': typeof LocaleAdminListingsNewRoute
  '/$locale/admin/settings/$tab': typeof LocaleAdminSettingsTabRoute
  '/$locale/admin/inquiries/': typeof LocaleAdminInquiriesIndexRoute
  '/$locale/admin/listings/': typeof LocaleAdminListingsIndexRoute
  '/$locale/admin/settings/': typeof LocaleAdminSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/auth': typeof LocaleAuthRouteWithChildren
  '/$locale/immobilienbewertung': typeof LocaleImmobilienbewertungRoute
  '/$locale/kontakt': typeof LocaleKontaktRoute
  '/$locale/ueber-mich': typeof LocaleUeberMichRoute
  '/$locale/verkaufen': typeof LocaleVerkaufenRoute
  '/$locale/verkauft': typeof LocaleVerkauftRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/admin/analytics': typeof LocaleAdminAnalyticsRoute
  '/$locale/admin/content': typeof LocaleAdminContentRoute
  '/$locale/admin/team': typeof LocaleAdminTeamRoute
  '/$locale/auth/forgot-password': typeof LocaleAuthForgotPasswordRoute
  '/$locale/auth/login': typeof LocaleAuthLoginRoute
  '/$locale/auth/reset-password': typeof LocaleAuthResetPasswordRoute
  '/$locale/immobilien/$slug': typeof LocaleImmobilienSlugRoute
  '/$locale/admin': typeof LocaleAdminIndexRoute
  '/$locale/immobilien': typeof LocaleImmobilienIndexRoute
  '/$locale/admin/inquiries/$id': typeof LocaleAdminInquiriesIdRoute
  '/$locale/admin/listings/$id': typeof LocaleAdminListingsIdRoute
  '/$locale/admin/listings/new': typeof LocaleAdminListingsNewRoute
  '/$locale/admin/settings/$tab': typeof LocaleAdminSettingsTabRoute
  '/$locale/admin/inquiries': typeof LocaleAdminInquiriesIndexRoute
  '/$locale/admin/listings': typeof LocaleAdminListingsIndexRoute
  '/$locale/admin/settings': typeof LocaleAdminSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/admin': typeof LocaleAdminRouteWithChildren
  '/$locale/auth': typeof LocaleAuthRouteWithChildren
  '/$locale/immobilienbewertung': typeof LocaleImmobilienbewertungRoute
  '/$locale/kontakt': typeof LocaleKontaktRoute
  '/$locale/ueber-mich': typeof LocaleUeberMichRoute
  '/$locale/verkaufen': typeof LocaleVerkaufenRoute
  '/$locale/verkauft': typeof LocaleVerkauftRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/admin/analytics': typeof LocaleAdminAnalyticsRoute
  '/$locale/admin/content': typeof LocaleAdminContentRoute
  '/$locale/admin/inquiries': typeof LocaleAdminInquiriesRouteWithChildren
  '/$locale/admin/listings': typeof LocaleAdminListingsRouteWithChildren
  '/$locale/admin/settings': typeof LocaleAdminSettingsRouteWithChildren
  '/$locale/admin/team': typeof LocaleAdminTeamRoute
  '/$locale/auth/forgot-password': typeof LocaleAuthForgotPasswordRoute
  '/$locale/auth/login': typeof LocaleAuthLoginRoute
  '/$locale/auth/reset-password': typeof LocaleAuthResetPasswordRoute
  '/$locale/immobilien/$slug': typeof LocaleImmobilienSlugRoute
  '/$locale/admin/': typeof LocaleAdminIndexRoute
  '/$locale/immobilien/': typeof LocaleImmobilienIndexRoute
  '/$locale/admin/inquiries/$id': typeof LocaleAdminInquiriesIdRoute
  '/$locale/admin/listings/$id': typeof LocaleAdminListingsIdRoute
  '/$locale/admin/listings/new': typeof LocaleAdminListingsNewRoute
  '/$locale/admin/settings/$tab': typeof LocaleAdminSettingsTabRoute
  '/$locale/admin/inquiries/': typeof LocaleAdminInquiriesIndexRoute
  '/$locale/admin/listings/': typeof LocaleAdminListingsIndexRoute
  '/$locale/admin/settings/': typeof LocaleAdminSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/admin'
    | '/$locale/auth'
    | '/$locale/immobilienbewertung'
    | '/$locale/kontakt'
    | '/$locale/ueber-mich'
    | '/$locale/verkaufen'
    | '/$locale/verkauft'
    | '/$locale/'
    | '/$locale/admin/analytics'
    | '/$locale/admin/content'
    | '/$locale/admin/inquiries'
    | '/$locale/admin/listings'
    | '/$locale/admin/settings'
    | '/$locale/admin/team'
    | '/$locale/auth/forgot-password'
    | '/$locale/auth/login'
    | '/$locale/auth/reset-password'
    | '/$locale/immobilien/$slug'
    | '/$locale/admin/'
    | '/$locale/immobilien/'
    | '/$locale/admin/inquiries/$id'
    | '/$locale/admin/listings/$id'
    | '/$locale/admin/listings/new'
    | '/$locale/admin/settings/$tab'
    | '/$locale/admin/inquiries/'
    | '/$locale/admin/listings/'
    | '/$locale/admin/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/auth'
    | '/$locale/immobilienbewertung'
    | '/$locale/kontakt'
    | '/$locale/ueber-mich'
    | '/$locale/verkaufen'
    | '/$locale/verkauft'
    | '/$locale'
    | '/$locale/admin/analytics'
    | '/$locale/admin/content'
    | '/$locale/admin/team'
    | '/$locale/auth/forgot-password'
    | '/$locale/auth/login'
    | '/$locale/auth/reset-password'
    | '/$locale/immobilien/$slug'
    | '/$locale/admin'
    | '/$locale/immobilien'
    | '/$locale/admin/inquiries/$id'
    | '/$locale/admin/listings/$id'
    | '/$locale/admin/listings/new'
    | '/$locale/admin/settings/$tab'
    | '/$locale/admin/inquiries'
    | '/$locale/admin/listings'
    | '/$locale/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/admin'
    | '/$locale/auth'
    | '/$locale/immobilienbewertung'
    | '/$locale/kontakt'
    | '/$locale/ueber-mich'
    | '/$locale/verkaufen'
    | '/$locale/verkauft'
    | '/$locale/'
    | '/$locale/admin/analytics'
    | '/$locale/admin/content'
    | '/$locale/admin/inquiries'
    | '/$locale/admin/listings'
    | '/$locale/admin/settings'
    | '/$locale/admin/team'
    | '/$locale/auth/forgot-password'
    | '/$locale/auth/login'
    | '/$locale/auth/reset-password'
    | '/$locale/immobilien/$slug'
    | '/$locale/admin/'
    | '/$locale/immobilien/'
    | '/$locale/admin/inquiries/$id'
    | '/$locale/admin/listings/$id'
    | '/$locale/admin/listings/new'
    | '/$locale/admin/settings/$tab'
    | '/$locale/admin/inquiries/'
    | '/$locale/admin/listings/'
    | '/$locale/admin/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/verkauft': {
      id: '/$locale/verkauft'
      path: '/verkauft'
      fullPath: '/$locale/verkauft'
      preLoaderRoute: typeof LocaleVerkauftRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/verkaufen': {
      id: '/$locale/verkaufen'
      path: '/verkaufen'
      fullPath: '/$locale/verkaufen'
      preLoaderRoute: typeof LocaleVerkaufenRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/ueber-mich': {
      id: '/$locale/ueber-mich'
      path: '/ueber-mich'
      fullPath: '/$locale/ueber-mich'
      preLoaderRoute: typeof LocaleUeberMichRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/kontakt': {
      id: '/$locale/kontakt'
      path: '/kontakt'
      fullPath: '/$locale/kontakt'
      preLoaderRoute: typeof LocaleKontaktRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/immobilienbewertung': {
      id: '/$locale/immobilienbewertung'
      path: '/immobilienbewertung'
      fullPath: '/$locale/immobilienbewertung'
      preLoaderRoute: typeof LocaleImmobilienbewertungRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/auth': {
      id: '/$locale/auth'
      path: '/auth'
      fullPath: '/$locale/auth'
      preLoaderRoute: typeof LocaleAuthRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin': {
      id: '/$locale/admin'
      path: '/admin'
      fullPath: '/$locale/admin'
      preLoaderRoute: typeof LocaleAdminRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/immobilien/': {
      id: '/$locale/immobilien/'
      path: '/immobilien'
      fullPath: '/$locale/immobilien/'
      preLoaderRoute: typeof LocaleImmobilienIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/admin/': {
      id: '/$locale/admin/'
      path: '/'
      fullPath: '/$locale/admin/'
      preLoaderRoute: typeof LocaleAdminIndexRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/immobilien/$slug': {
      id: '/$locale/immobilien/$slug'
      path: '/immobilien/$slug'
      fullPath: '/$locale/immobilien/$slug'
      preLoaderRoute: typeof LocaleImmobilienSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/auth/reset-password': {
      id: '/$locale/auth/reset-password'
      path: '/reset-password'
      fullPath: '/$locale/auth/reset-password'
      preLoaderRoute: typeof LocaleAuthResetPasswordRouteImport
      parentRoute: typeof LocaleAuthRoute
    }
    '/$locale/auth/login': {
      id: '/$locale/auth/login'
      path: '/login'
      fullPath: '/$locale/auth/login'
      preLoaderRoute: typeof LocaleAuthLoginRouteImport
      parentRoute: typeof LocaleAuthRoute
    }
    '/$locale/auth/forgot-password': {
      id: '/$locale/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/$locale/auth/forgot-password'
      preLoaderRoute: typeof LocaleAuthForgotPasswordRouteImport
      parentRoute: typeof LocaleAuthRoute
    }
    '/$locale/admin/team': {
      id: '/$locale/admin/team'
      path: '/team'
      fullPath: '/$locale/admin/team'
      preLoaderRoute: typeof LocaleAdminTeamRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/settings': {
      id: '/$locale/admin/settings'
      path: '/settings'
      fullPath: '/$locale/admin/settings'
      preLoaderRoute: typeof LocaleAdminSettingsRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/listings': {
      id: '/$locale/admin/listings'
      path: '/listings'
      fullPath: '/$locale/admin/listings'
      preLoaderRoute: typeof LocaleAdminListingsRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/inquiries': {
      id: '/$locale/admin/inquiries'
      path: '/inquiries'
      fullPath: '/$locale/admin/inquiries'
      preLoaderRoute: typeof LocaleAdminInquiriesRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/content': {
      id: '/$locale/admin/content'
      path: '/content'
      fullPath: '/$locale/admin/content'
      preLoaderRoute: typeof LocaleAdminContentRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/analytics': {
      id: '/$locale/admin/analytics'
      path: '/analytics'
      fullPath: '/$locale/admin/analytics'
      preLoaderRoute: typeof LocaleAdminAnalyticsRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/admin/settings/': {
      id: '/$locale/admin/settings/'
      path: '/'
      fullPath: '/$locale/admin/settings/'
      preLoaderRoute: typeof LocaleAdminSettingsIndexRouteImport
      parentRoute: typeof LocaleAdminSettingsRoute
    }
    '/$locale/admin/listings/': {
      id: '/$locale/admin/listings/'
      path: '/'
      fullPath: '/$locale/admin/listings/'
      preLoaderRoute: typeof LocaleAdminListingsIndexRouteImport
      parentRoute: typeof LocaleAdminListingsRoute
    }
    '/$locale/admin/inquiries/': {
      id: '/$locale/admin/inquiries/'
      path: '/'
      fullPath: '/$locale/admin/inquiries/'
      preLoaderRoute: typeof LocaleAdminInquiriesIndexRouteImport
      parentRoute: typeof LocaleAdminInquiriesRoute
    }
    '/$locale/admin/settings/$tab': {
      id: '/$locale/admin/settings/$tab'
      path: '/$tab'
      fullPath: '/$locale/admin/settings/$tab'
      preLoaderRoute: typeof LocaleAdminSettingsTabRouteImport
      parentRoute: typeof LocaleAdminSettingsRoute
    }
    '/$locale/admin/listings/new': {
      id: '/$locale/admin/listings/new'
      path: '/new'
      fullPath: '/$locale/admin/listings/new'
      preLoaderRoute: typeof LocaleAdminListingsNewRouteImport
      parentRoute: typeof LocaleAdminListingsRoute
    }
    '/$locale/admin/listings/$id': {
      id: '/$locale/admin/listings/$id'
      path: '/$id'
      fullPath: '/$locale/admin/listings/$id'
      preLoaderRoute: typeof LocaleAdminListingsIdRouteImport
      parentRoute: typeof LocaleAdminListingsRoute
    }
    '/$locale/admin/inquiries/$id': {
      id: '/$locale/admin/inquiries/$id'
      path: '/$id'
      fullPath: '/$locale/admin/inquiries/$id'
      preLoaderRoute: typeof LocaleAdminInquiriesIdRouteImport
      parentRoute: typeof LocaleAdminInquiriesRoute
    }
  }
}

interface LocaleAdminInquiriesRouteChildren {
  LocaleAdminInquiriesIdRoute: typeof LocaleAdminInquiriesIdRoute
  LocaleAdminInquiriesIndexRoute: typeof LocaleAdminInquiriesIndexRoute
}

const LocaleAdminInquiriesRouteChildren: LocaleAdminInquiriesRouteChildren = {
  LocaleAdminInquiriesIdRoute: LocaleAdminInquiriesIdRoute,
  LocaleAdminInquiriesIndexRoute: LocaleAdminInquiriesIndexRoute,
}

const LocaleAdminInquiriesRouteWithChildren =
  LocaleAdminInquiriesRoute._addFileChildren(LocaleAdminInquiriesRouteChildren)

interface LocaleAdminListingsRouteChildren {
  LocaleAdminListingsIdRoute: typeof LocaleAdminListingsIdRoute
  LocaleAdminListingsNewRoute: typeof LocaleAdminListingsNewRoute
  LocaleAdminListingsIndexRoute: typeof LocaleAdminListingsIndexRoute
}

const LocaleAdminListingsRouteChildren: LocaleAdminListingsRouteChildren = {
  LocaleAdminListingsIdRoute: LocaleAdminListingsIdRoute,
  LocaleAdminListingsNewRoute: LocaleAdminListingsNewRoute,
  LocaleAdminListingsIndexRoute: LocaleAdminListingsIndexRoute,
}

const LocaleAdminListingsRouteWithChildren =
  LocaleAdminListingsRoute._addFileChildren(LocaleAdminListingsRouteChildren)

interface LocaleAdminSettingsRouteChildren {
  LocaleAdminSettingsTabRoute: typeof LocaleAdminSettingsTabRoute
  LocaleAdminSettingsIndexRoute: typeof LocaleAdminSettingsIndexRoute
}

const LocaleAdminSettingsRouteChildren: LocaleAdminSettingsRouteChildren = {
  LocaleAdminSettingsTabRoute: LocaleAdminSettingsTabRoute,
  LocaleAdminSettingsIndexRoute: LocaleAdminSettingsIndexRoute,
}

const LocaleAdminSettingsRouteWithChildren =
  LocaleAdminSettingsRoute._addFileChildren(LocaleAdminSettingsRouteChildren)

interface LocaleAdminRouteChildren {
  LocaleAdminAnalyticsRoute: typeof LocaleAdminAnalyticsRoute
  LocaleAdminContentRoute: typeof LocaleAdminContentRoute
  LocaleAdminInquiriesRoute: typeof LocaleAdminInquiriesRouteWithChildren
  LocaleAdminListingsRoute: typeof LocaleAdminListingsRouteWithChildren
  LocaleAdminSettingsRoute: typeof LocaleAdminSettingsRouteWithChildren
  LocaleAdminTeamRoute: typeof LocaleAdminTeamRoute
  LocaleAdminIndexRoute: typeof LocaleAdminIndexRoute
}

const LocaleAdminRouteChildren: LocaleAdminRouteChildren = {
  LocaleAdminAnalyticsRoute: LocaleAdminAnalyticsRoute,
  LocaleAdminContentRoute: LocaleAdminContentRoute,
  LocaleAdminInquiriesRoute: LocaleAdminInquiriesRouteWithChildren,
  LocaleAdminListingsRoute: LocaleAdminListingsRouteWithChildren,
  LocaleAdminSettingsRoute: LocaleAdminSettingsRouteWithChildren,
  LocaleAdminTeamRoute: LocaleAdminTeamRoute,
  LocaleAdminIndexRoute: LocaleAdminIndexRoute,
}

const LocaleAdminRouteWithChildren = LocaleAdminRoute._addFileChildren(
  LocaleAdminRouteChildren,
)

interface LocaleAuthRouteChildren {
  LocaleAuthForgotPasswordRoute: typeof LocaleAuthForgotPasswordRoute
  LocaleAuthLoginRoute: typeof LocaleAuthLoginRoute
  LocaleAuthResetPasswordRoute: typeof LocaleAuthResetPasswordRoute
}

const LocaleAuthRouteChildren: LocaleAuthRouteChildren = {
  LocaleAuthForgotPasswordRoute: LocaleAuthForgotPasswordRoute,
  LocaleAuthLoginRoute: LocaleAuthLoginRoute,
  LocaleAuthResetPasswordRoute: LocaleAuthResetPasswordRoute,
}

const LocaleAuthRouteWithChildren = LocaleAuthRoute._addFileChildren(
  LocaleAuthRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAdminRoute: typeof LocaleAdminRouteWithChildren
  LocaleAuthRoute: typeof LocaleAuthRouteWithChildren
  LocaleImmobilienbewertungRoute: typeof LocaleImmobilienbewertungRoute
  LocaleKontaktRoute: typeof LocaleKontaktRoute
  LocaleUeberMichRoute: typeof LocaleUeberMichRoute
  LocaleVerkaufenRoute: typeof LocaleVerkaufenRoute
  LocaleVerkauftRoute: typeof LocaleVerkauftRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleImmobilienSlugRoute: typeof LocaleImmobilienSlugRoute
  LocaleImmobilienIndexRoute: typeof LocaleImmobilienIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAdminRoute: LocaleAdminRouteWithChildren,
  LocaleAuthRoute: LocaleAuthRouteWithChildren,
  LocaleImmobilienbewertungRoute: LocaleImmobilienbewertungRoute,
  LocaleKontaktRoute: LocaleKontaktRoute,
  LocaleUeberMichRoute: LocaleUeberMichRoute,
  LocaleVerkaufenRoute: LocaleVerkaufenRoute,
  LocaleVerkauftRoute: LocaleVerkauftRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleImmobilienSlugRoute: LocaleImmobilienSlugRoute,
  LocaleImmobilienIndexRoute: LocaleImmobilienIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
